name: CI/CD Pipeline for PKPL Project

on:
  push:
    branches:
      - main # Ini berarti workflow akan berjalan setiap kali ada push ke branch 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Runner yang digunakan untuk menjalankan job ini

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Mengambil kode dari repositori

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Mengatur Docker Buildx untuk build multi-platform

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }} # Menggunakan GitHub Secrets untuk kredensial

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: . # Konteks build (direktori tempat Dockerfile berada, '.' berarti root repo)
          push: true # Mendorong image ke registry setelah build
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/uas-pkpl-belinda:latest # Nama image:tag
            ${{ secrets.DOCKER_USERNAME }}/uas-pkpl-belinda:${{ github.sha }} # Contoh tag dengan commit SHA
          cache-from: type=gha # Opsional: Menggunakan cache GitHub Actions untuk build lebih cepat
          cache-to: type=gha,mode=max # Opsional: Menyimpan cache untuk build selanjutnya
